service:
  name: hyu-oms-backend-serverless-nodejs

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'ap-northeast-1'}
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
